### ISSUE TITLE
Inconsistency in GS1 Digital Link data attribute flag

### ISSUE THREAD

**Issue by KDean-Dolphin** [gs1/gs1-syntax-dictionary#11]
The '?' character indicates an "AI that is permitted as a GS1 Digital Link data attribute". The naive interpretation of this flag is that the AI is permitted in the query string, but every AI with the dlpkey attribute set also has this flag set, so this could lead to an incorrect implementation where a dlpkey AI ends up in the wrong place, e.g., https://id.gs1.org/00/095212340000000006?00=095212340000000006.

Secondary keys, such as AI 21, don't have this flag set.

In my opinion, this flag should be removed for dlpkey AIs.

**Comment by mgh128** [comment]
It's probably there to permit situations where a product instance is also later an asset and we want to support the expression of e.g. SGTIN in the URI path info and GIAI in the URI query string

**Comment by terryburton** [comment]
Agreed. The intent of the "?" flag is to align with the "data attribute" AIs in the grammar. It's an attribute filter so the approach was "be inclusive" to maintain existing behaviours, and therefore likely overly broad.

It was added because with the latest URI spec it became clearer that there are AIs that are never intended to appear in a DL URI, e.g. (8200).

(With the URI spec that was available when the dictionary was derived it was not clear whether certain AIs were missing due to misalignment with the GenSpecs or by intent.)

I'll work through the list.

**Comment by terryburton** [comment]
Fixed with eb948e418253277237d49829f9010dcf3bbe32e0.

**Comment by KDean-Dolphin** [comment]
AI 415 is still showing '?' and "dlpkey".

**Comment by terryburton** [comment]
> AI 415 is still showing '?' and "dlpkey".

Thanks for checking. Fixed with ca3344bd3bfb00de8672a8adc450186da07fe2e9.
